### ISSUE TITLE
Misleading exception when handling requests

### ISSUE THREAD

**Issue by thiagoss** [OctahedronBR/cotopaxi-core#10]
When there is no response specified for a url handler method, cotopaxi throws a:

SEVERE: Servlet cannot determine neither a controller, nor a error handler, for url <url>

It handles the request, but it doesn't have a response indication (ok, notfound, error, ...), the html page returned even indicates this to the user, it just prints the wrong exception,

**Comment by daniloqueiroz** [comment]
Exception was not removed. It is a usage error, that should be detected as soon as possible by the programmer. I've just changed the exception message to a more friendly one.
